 spring:
   data:
     mongodb:
       host: ds115866.mlab.com
       port: 37101
       database: hangman
       username: test
       password: test  	
 redis:
   host: 192.168.56.101
   port: 6379

